name: example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # 状态管理
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # 网络层
  dio: ^5.4.0
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  
  # 路由管理
  go_router: ^15.2.0
  
  # 本地存储
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # WebSocket
  web_socket_channel: ^3.0.3
  
  # 环境配置
  flutter_dotenv: ^5.1.0
  
  # 工具包
  logger: ^2.0.2+1
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  retrofit_generator: ^9.2.0
  hive_generator: ^2.0.1
  freezed: ^2.4.6
  persistent_bottom_nav_bar_v2: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - .env.development
    - .env.production
    - assets/images/
    - assets/icons/
